name: Daily DSA WhatsApp Reminder

on:
  schedule:
    - cron: '30 13 * * *'   # 7:00 PM IST
  workflow_dispatch:       # allows manual run

jobs:
  send-whatsapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas twilio gspread oauth2client

      - name: Run script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        run: |
          python send_whatsapp.py
